### ISSUE TITLE
Few issues with s7 edge - oreo - 

### ISSUE THREAD

**Issue by JustHavingALook** [therealahrion/Xposed-Framework-Unity#2]
I flashed unity installer via Magisk - v89/90b3r13 - 9.20.2018

- Cannot read log/data/user_de/0/de.robv.android.xposed.installer/log/error.log (No such file or directory)

- Corrupted SdCard into non-readable or writable

- Xposed is not yet compatible with sdk26 Arm64-v8a

Apologies if I'm forgetting to add all relevant information, I'm new to development and git.

**Comment by JustHavingALook** [comment]
Apologies, wrong place to post the issue :)

**Comment by Zackptg5** [comment]
For the first issue, that's a common one lots of people have, just Google it and you'll see tons of potential fixes.
This mod doesn't cause issue 2 however issue 2 could cause issue 1
Xposed is compatible with sdk26 (it's compatible up to sdk 27) so not sure what you mean there

**Comment by JustHavingALook** [comment]
Hello Zack,

I've attached a link for further reference/understanding for you.
If you need any logs/extra information, just let me know. 

Thanks heaps :)
Regards,
Brand

Backup link: https://ibb.co/ewcCdA

![Not yet compatible with sdk26](https://ibb.co/ewcCdA)

**Comment by dariusity** [comment]
I get bootloop as well after flashing via both twrp recovery and magisk manager.

Device: Samsung Galaxy J200GU/j2lte
OS: Android Lollipop 5.1
Magisk Manager v6.01
Magisk v17.1
Xposed Framework v89/90b3r14

Thanks

**Comment by Zackptg5** [comment]
@JustHavingALook

The image looks fine, green checkbox means it's working

@dariusity

I suggest you read into Xposed compatibilit on the official rovo89 Xposed threads. You probably need wanna version for Samsung lollipop if you're on touchwiz

**Comment by dariusity** [comment]
Thanks for the heads up. Cheers.
