### ISSUE TITLE
Xposed Framework not installed [Oneplus One] 

### ISSUE THREAD

**Issue by donpapadee** [therealahrion/Xposed-Framework-Unity#4]
I've installed xposed using the the unity installer from magisk but it always say it isn't installed!
Attached is a copy of the logs and picture, thanks ☺ 
![screenshot_20190108-230728_xposed_installer](https://user-images.githubusercontent.com/39539788/50878541-d7ed7480-139c-11e9-8dd3-ab62d2bff921.png)
[xposed_error_20190108_230556.log](https://github.com/therealahrion/Xposed-Framework-Unity/files/2739475/xposed_error_20190108_230556.log)
[xposed_error_20190108_230544.log](https://github.com/therealahrion/Xposed-Framework-Unity/files/2739476/xposed_error_20190108_230544.log)

**Comment by Zackptg5** [comment]
This problem has been discussed numerous times on xda. Search the support thread and original Xposed threads for solutions. GitHub issues are a place for bugs, not support
