### ISSUE TITLE
Stuck on Boot (Redmi 4 Prime MIUI Global Stable 10.2.1.0)

### ISSUE THREAD

**Issue by DzikrRully** [therealahrion/Xposed-Framework-Unity#5]
Stuck on Boot on Redmi 4 Prime MIUI Global Stable 10.2.1.0.

**Comment by Zackptg5** [comment]
Make a proper bug report or don't bother. XDA thread is a better place for this but this is also just an installer for xposed - not the actual xposed repo so you'll probably want to go there
